server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: foodservice_route
          uri: http://localhost:8090/
          predicates:
            - Path=/foodservice/**
          filters:
            - RewritePath=/foodservice/(?<segment>.*), /$\{segment}
      default-filters:
        - AddResponseHeader=cloudnativeworkshop, Microservice

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug